### ISSUE TITLE
Visually improve the site

### ISSUE THREAD

**Issue by int-code** [int-code/url-shortener#2]
Improve the design of the html files

**Comment by Divjyo15** [comment]
hi @int-code can you assign to me

**Comment by int-code** [comment]
Assigned you! If you need anything, just ask

**Comment by Divjyo15** [comment]
hey,what type of design you want.can you  plz elaborate more.

**Comment by int-code** [comment]
Anything that is better than it is currently. I'm not much of a design person so I'll leave that to you. Would be nice if it looked a bit more modern. It's a pretty simple site so not much to do tbh

**Comment by Divjyo15** [comment]
hey @int-code I am sorry...right now i am working upon different issue

**Comment by int-code** [comment]
no worries!
